apiVersion: apps/v1
kind: Deployment
metadata:
   name: soppy-app-deployment
   labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: soppy-app
          image: danikohale/soppy
          ports:
            - containerPort: 80
